interface b2Vec2 {
	attribute float x;
	attribute float y;
};

interface b2AABB {
	[Value] attribute b2Vec2 lowerBound;
	[Value] attribute b2Vec2 upperBound;
};

interface Collisions {
	void Collisions();
	[Value] b2AABB b2AABB_ConstructFromCenterSize(float x, float y, float w, float h);
	[Value] b2AABB b2AABB_ExtendBySize([Ref] b2AABB a, float w, float h);
	[Value] b2Vec2 test([Ref] b2AABB a, float tx, float ty);
	b2AABB addAABB(DOMString id, float x, float y, float w, float h);
	void eraseAABB(DOMString id);
	void clear();
};